import = ["/Users/phaazon/.config/alacritty/themes/catppuccin-macchiato.toml"]

[cursor.style]
blinking = "On"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Thin"

[selection]
save_to_clipboard = true

[window]
option_as_alt = "OnlyRight"
