#!/bin/bash

case $# in
  0)
    # write the marks to stdout
    marks=$(i3-msg -t get_marks | tr -d "[]\"" | tr ',' '\n')
    for mark in $marks; do
      echo -e "$mark\0"
    done
    ;;

  1)
    i3-msg "[con_mark=\"$1\"] focus" &> /dev/null
    ;;

  *)
    echo "MEH"
    exit 1
    ;;
esac
