theme = "catppuccin_macchiato"

[editor]
scroll-lines = 1
cursorline = true
auto-save = true
completion-trigger-len = 1
true-color = true
color-modes = true
auto-pairs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true

[keys.normal]
c = "move_char_left"
r = "move_char_right"
t = "move_line_down"
s = "move_line_up"
g = { c = "goto_line_start", r = "goto_line_end", h = "no_op", l = "no_op" }
space = { w = { c = "jump_view_left", r = "jump_view_right", t = "jump_view_down", s = "jump_view_up", o = "hsplit" } }
"é" = "move_next_word_start"
"É" = "move_next_long_word_start"
h = "replace"
H = "replace_with_yanked"
l = "change_selection"
z = "select_regex"
"à" = "find_till_char"

[keys.select]
c = "extend_char_left"
r = "extend_char_right"
t = "extend_line_down"
s = "extend_line_up"
g = { c = "goto_line_start", r = "goto_line_end", h = "no_op", l = "no_op" }
"é" = "move_next_word_start"
"É" = "move_next_long_word_start"
h = "replace"
H = "replace_with_yanked"
l = "change_selection"
z = "select_regex"
"à" = "find_till_char"
