#!/bin/sh

# Monitor and workspaces.
DESKTOP_HOSTNAME="orchid"
LAPTOP_HOSTNAME="monoid-prime"
HOST=$(hostname)

case "$HOST" in
  "$DESKTOP_HOSTNAME")
    bspc monitor DP-2 -d " web" " code" " sys" " media" " misc"
    bspc monitor HDMI-0 -d " foo" " sushi" " hotdog" " spotify" "ﳴ chat"
    ;;

  "$LAPTOP_HOSTNAME")
    bspc monitor eDP1 -d web code 3 4 5 6 7 doc spotify chat
    ;;

  *)
    bspc monitor I II III IV V VI VII IX X
    ;;
esac

# Visual.
bspc config top_padding               20
bspc config window_gap                10
bspc config border_width               2
bspc config normal_border_color  #ff0000
bspc config active_border_color  #ff0000
bspc config focused_border_color #00ff00
bspc config borderless_monocle     false
bspc config gapless_monocle        false
bspc config top_monocle_padding        0
bspc config split_ratio              0.5

# Behavior.
bspc config pointer_modifier             mod1
bspc config automatic_scheme        alternate
bspc config focus_follows_pointer        true
bspc config pointer_follows_monitor      true
bspc config honor_size_hints            false

# Autostart.
sxhkd &
dunst &
nitrogen --restore &
picom --experimental-backends
polybar desktop-primary &
polybar desktop-secondary &

case "$HOST" in
  "$DESKTOP_HOSTNAME")
    polybar desktop-primary &
    polybar desktop-secondary &
    ;;

  "$LAPTOP_HOSTNAME")
    polybar laptop-primary &
    ;;
esac

xset r rate 200 30

# Window rules.
# none so far
