#!/bin/sh

# Monitor and workspaces.
DESKTOP_HOSTNAME="orchid"
LAPTOP_HOSTNAME="monoid-prime"
HOST=$(hostname)

case "$HOST" in
  "$DESKTOP_HOSTNAME")
    bspc monitor DP-2 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6 7 8 9 0
    ;;

  "$LAPTOP_HOSTNAME")
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
    ;;

  *)
    bspc monitor 1 2 3 4 5 6 7 8 9 0
    ;;
esac

# Visual.
bspc config top_padding               20
bspc config window_gap                10
bspc config border_width               2
bspc config normal_border_color  "#363a4e"
bspc config active_border_color  "#b2c9ec"
bspc config focused_border_color "#a0c980"
bspc config presel_feedback_color "#da7cf8"
bspc config borderless_monocle     false
bspc config gapless_monocle        false
bspc config top_monocle_padding        0
bspc config split_ratio              0.5

# Behavior.
bspc config pointer_modifier             mod1
bspc config automatic_scheme        alternate
bspc config focus_follows_pointer        true
bspc config pointer_follows_monitor      true
bspc config honor_size_hints            false

# Autostart.
sxhkd &
dunst &
nitrogen --restore &
# picom --experimental-backends &
xsetroot -cursor_name left_ptr
xset r rate 200 30

case "$HOST" in
  "$DESKTOP_HOSTNAME")
    polybar desktop-primary &
    polybar desktop-secondary &
    ;;

  "$LAPTOP_HOSTNAME")
    polybar laptop-primary &
    ;;
esac
