keybinding:
  universal:
    prevItem-alt: 's'
    nextItem-alt: 't'
    prevBlock-alt: 'c'
    nextBlock-alt: 'r'
    refresh: '$'
    prevTab: '('
    nextTab: ')'
  branches:
    checkoutBranchByName: null
    rebaseBranch: 'R'
    renameBranch: null
  files:
    commitChanges: null
    refreshFiles: null
    stageAllChanges: null
  commits:
    squashDown: null
    renameCommit: null
    cherryPickCopy: null
  commitFiles:
    checkoutCommitFile: null
  stash:
    renameStash: null
