# Options, highlighters, etc.
colorscheme catppuccin_macchiato
set global indentwidth 2

add-highlighter global/git-diff flag-lines Default git_diff_flags
add-highlighter global/number-lines number-lines -hlcursor
add-highlighter global/fixme-todo-note regex '(?:#+|//+|--+|;;+)\s*(?:(FIXME:)|(TODO:)|(NOTE:))' 1:red+ib 2:green+ib 3:magenta+ib

## automatically update git diff, if needed
hook global BufCreate .* %{git show-diff} # FIXME: not sure it’s the best way
hook global BufWritePost .* %{git update-diff}

# Commands

# window mode
declare-user-mode window

## kitty integration
define-command kitty-split -params 1 -docstring 'split the current window according to the param (vsplit / hsplit)' %{
  evaluate-commands %sh{
    kitty @ launch --no-response --location $1 kak -c $kak_session
  }
}

## Some pickers
define-command -hidden open_buffer_picker %{
  prompt buffer: -menu -buffer-completion %{
    buffer %val{text}
  }
}

define-command -hidden open_file_picker %{
  prompt file: -menu -shell-script-candidates 'fd --type=file' %{
    edit -existing %val{text}
  }
}

define-command -hidden open_rg_picker %{
  prompt search: %{
    prompt refine: -menu -shell-script-candidates "rg -n '%val{text}'" %{
      eval "edit -existing  %sh{(cut -d ' ' -f 1 | tr ':' ' ' ) <<< $kak_text}"
    }
  }
}

## match mode (surround, etc.)
declare-user-mode match

define-command -hidden match-delete-surround -docstring 'delete surrounding key' %{
  on-key 'match-delete-surround-on-key'
}

define-command -hidden match-delete-surround-on-key %{
  execute-keys -draft '<a-a>%val{key}i<del><esc>a<backspace><esc>'
}

define-command surround-key -docstring 'surround key' %{
  on-key %{
    add-surrounding-pair %val{key} %val{key}
  }
}

define-command surround-tag -docstring 'surround tag' %{
  prompt surround-tag: %{
    add_surrounding_pair '<%val{text}>' '</%val{text}>'
  }
}
    
define-command -hidden add-surrounding-pair -params 2 %{
  evaluate-commands -save-regs '"' %{
    set-register '"' %arg{1}
    execute-keys -draft P
    set-register '"' %arg{2}
    execute-keys -draft p
  }
}

# LSP
eval %sh{kak-lsp --kakoune -s $kak_session}

## common optinos
lsp-auto-signature-help-enable
set global lsp_hover_anchor true
set global lsp_auto_show_code_actions true

## main hook for languages
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
  lsp-enable-window

  lsp-inlay-diagnostics-enable window
  lsp-inlay-hints-enable window
  lsp-inlay-code-lenses-enable window

  hook window BufWritePre .* lsp-formatting-sync
  hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
  hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
  hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
  hook -once -always window WinSetOption filetype=.* %{
      remove-hooks window semantic-tokens
  }
}

# keybindings

## bépo remapping
map global normal c h # left
map global normal t j # down
map global normal s k # up
map global normal r l # right
map global normal C H # extend left
map global normal T J # extend down
map global normal S K # extend up
map global normal R L # extend right
map global normal h t # until
map global normal j r # replace
map global normal k s # select
map global normal l c # change
map global normal H T # extend to next char
map global normal J R # replace with yanked
map global normal K S # split
map global normal L C # duplicate selection downwards
map global insert ' ' ' '
map global goto c h -docstring 'line begin' 
map global goto t j -docstring 'buffer bottom' 
map global goto s k -docstring 'buffer top' 
map global goto r l -docstring 'line end' 
map global view c h -docstring 'scroll left' 
map global view t j -docstring 'scroll up' 
map global view s k -docstring 'scroll down' 
map global view r l -docstring 'scroll right' 

## pickers
map global user b ':open_buffer_picker<ret>' -docstring 'pick buffer'
map global user f ':open_file_picker<ret>'   -docstring 'pick file'
map global user / ':open_rg_picker<ret>'     -docstring 'search project'

## match
map global normal m ':enter-user-mode match<ret>' -docstring 'match mode'
map global match m m                              -docstring 'select other matching delimiter'
map global match i '<a-i>'                        -docstring 'match inside'
map global match a '<a-a>'                        -docstring 'match around'
map global match d ':match-delete-surround<ret>'  -docstring 'delete surround'

## window management
map global user w ':enter-user-mode window<ret>' -docstring 'window mode'
map global window v ':kitty-split vsplit<ret>'   -docstring 'vertical split'
map global window o ':kitty-split hsplit<ret>'   -docstring 'horizontal split'

## git
declare-user-mode git
map global user g ':enter-user-mode git<ret>' -docstring 'git mode'
map global git p ':git prev-hunk<ret>'        -docstring 'goto previous hunk'
map global git n ':git next-hunk<ret>'        -docstring 'goto next hunk'

## LSP
declare-user-mode user-lsp
map global user l ':enter-user-mode user-lsp<ret>'      -docstring 'lsp mode'
map global user-lsp a ':lsp-code-actions<ret>'          -docstring 'code action'
map global user-lsp c ':lsp-code-lens<ret>'             -docstring 'execute code lens'
map global user-lsp d ':lsp-diagnostics<ret>'           -docstring 'list diagnostics'
map global user-lsp i ':lsp-incoming-calls<ret>'        -docstring 'incoming calls'
map global user-lsp I ':lsp-implementation<ret>'        -docstring 'list implementations'
map global user-lsp h ':lsp-highlight-references<ret>'  -docstring 'highlight references'
map global user-lsp k ':lsp-hover<ret>'                 -docstring 'hover'
map global user-lsp K ':lsp-hover-buffer<ret>'          -docstring 'hover in a dedicated buffer'
map global user-lsp p ':lsp-workspace-symbol-incr<ret>' -docstring 'pick workspace symbol'
map global user-lsp P ':lsp-workspace-symbol<ret>'      -docstring 'list workspace symbols'
map global user-lsp r ':lsp-rename-prompt<ret>'         -docstring 'rename'
map global user-lsp R ':lsp-references<ret>'            -docstring 'list references'
map global user-lsp o ':lsp-outgoing-calls<ret>'        -docstring 'outgoing calls'
map global user-lsp s ':lsp-goto-document-symbol<ret>'  -docstring 'pick document symbol'
map global user-lsp S ':lsp-document-symbol<ret>'       -docstring 'list workspace symbols'
map global user-lsp x ':lsp-find-error<ret>'            -docstring 'jump to the prev/next error'
map global user-lsp ( ':lsp-previous-function<ret>'     -docstring 'jump to the previous function'
map global user-lsp ) ':lsp-next-function<ret>'         -docstring 'jump to the next function'
