execute pathogen#infect()

source ~/.nvim/nvimrc.bepo
source ~/.nvim/plugin/fugitive.vim

set encoding=utf-8
scriptencoding utf-8

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set nobackup		" do not keep any backup file
set history=50		" keep 50 lines of command line history
set ruler           " show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set noswapfile
set hidden

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" Fuzzy search on ,f
" Fuzzy tag searc on ,t
noremap ,f :CtrlP<CR>
noremap ,t :CtrlPTag<CR>

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
syntax on
set hlsearch

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

endif " has("autocmd")

set colorcolumn=100
set statusline=%F%m%r%h%w\ ·\ %{&ff}\ ·\ %Y\ ·\ %04l:%03v\ (%03p%%)\ ·\ %L\ lines
set statusline+=\ ·\ %{fugitive#statusline()}
set tabstop=2
set shiftwidth=2
set smartindent " sure about it ? :(
set expandtab
set autoindent	" always set autoindenting on
set backupdir=/var/tmp
set dir=/var/tmp

let mapleader="è"
lmap <S-Space> <ESC>
 
" Change the style of the netrw's output
let g:netrw_liststyle=3
colorscheme desertEx
set laststatus=2

nmap <C-S-P> :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

if has("gui")
  set guioptions-=m
  set guioptions-=T
  set guioptions-=r
  set guioptions-=L
endif

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component': {
      \   'readonly': '%{&filetype=="help"?"":&readonly?"×":""}',
      \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}',
      \   'fugitive': '%{exists("*fugitive#head")?fugitive#head():""}'
      \ },
      \ 'component_visible_condition': {
      \   'readonly': '(&filetype!="help"&& &readonly)',
      \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))',
      \   'fugitive': '(exists("*fugitive#head") && ""!=fugitive#head())'
      \ },
      \ 'separator': { 'left': '', 'right': '' },
      \ 'subseparator': { 'left': '|', 'right': '|' }
      \ }

set noshowmode
