require 'config.vim'
require 'config.keybindings'
require 'config.pkg'
require 'config.colorscheme'
require 'config.lsp'
require 'config.treesitter'
require 'config.telescope'
require 'config.statusline'
