#!/bin/sh
#
# This script allows to merge a branch on the current branch easily.

header="Select a branch to merge"
choice=$(git branch | rg -v "^\*" | tr -d ' ' | fzf \
  --header="$header" \
  --prompt="Merge: " \
)

[ $? = 0 ] && git merge $choice
